s3_bucket_name                   = "sandbox-tf-test"
aws_region                       = "us-east-1"
state_key                        = "devops.tfstate"
environment_name                 = "dev"
dynamodb_table_name              = "sandbox-bkp4"
